# Generated by Django 5.0.1 on 2024-01-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='issue',
            new_name='issue_id',
        ),
    ]
