# Generated by Django 5.0.1 on 2024-01-29 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_issue_solution_issue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.issues'),
        ),
    ]
