# Generated by Django 5.0.2 on 2024-02-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=20),
        ),
    ]
