# Generated by Django 5.0.2 on 2024-02-23 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_issues_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
