# Generated by Django 5.0.2 on 2024-02-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_issues_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='issue_id',
            new_name='issue',
        ),
    ]
