# Generated by Django 5.0.2 on 2024-03-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_issues_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.levels'),
        ),
    ]
