# Generated by Django 5.0.2 on 2024-03-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_issues_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issues',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.levels'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='level',
            field=models.ForeignKey(blank=True, default=8, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.levels'),
        ),
    ]
