# Generated by Django 5.0.2 on 2024-03-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_issues_options_customuser_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='levels',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.levels'),
        ),
    ]
