# Generated by Django 5.0.2 on 2024-03-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_levels_options_levels_order_alter_issues_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Answered'), (3, 'forwarded')], default=1),
        ),
    ]
