COMPLAINT_STATUS_PENDING = 1
COMPLAINT_STATUS_ANSWERED = 2
COMPLAINT_STATUS_FORWARDED=3


COMPLAINT_STATUS_CHOICES = (
    (COMPLAINT_STATUS_PENDING, "Pending"),
    (COMPLAINT_STATUS_ANSWERED, "Answered"),
      (COMPLAINT_STATUS_FORWARDED, "forwarded"),
    
     
)

